# Project: AllMovesOfKnight
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = AllMovesOfKnight.o
LINKOBJ  = AllMovesOfKnight.o
LIBS     = -L"E:/Programs/Dev-Cpp/MinGW64/lib" -L"E:/Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/Programs/Dev-Cpp/MinGW64/include" -I"E:/Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/Programs/Dev-Cpp/MinGW64/include" -I"E:/Programs/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/Programs/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = AllMovesOfKnight.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

AllMovesOfKnight.o: AllMovesOfKnight.c
	$(CC) -c AllMovesOfKnight.c -o AllMovesOfKnight.o $(CFLAGS)
