# Project: KnightMoves
# Makefile created by Dev-C++ 5.4.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = knightMoves.o
LINKOBJ  = knightMoves.o
LIBS     = -L"E:/English Program/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -pthread -g3
INCS     = -I"E:/English Program/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
CXXINCS  = -I"E:/English Program/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include"
BIN      = KnightMoves.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

knightMoves.o: knightMoves.c
	$(CC) -c knightMoves.c -o knightMoves.o $(CFLAGS)
